// SERVICES
export const GET_ALL_SERVICE = "GET_ALL_SERVICE"
export const GET_ONE_SERVICE = "GET_ONE_SERVICE"
export const SET_SERVICE_LOADING = "SET_SERVICE_LOADING"
export const SET_SERVICE_ERROR = "SET_SERVICE_ERROR"
export const CREATE_SERVICE = "CREATE_SERVICE"
export const EDIT_SERVICE = "EDIT_SERVICE"
export const DELETE_SERVICE = "READ_ALL_SERVICE"
